# Generated by Django 5.2.5 on 2025-11-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='location',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='dropoff_address',
            field=models.CharField(default='unknown', help_text='Hospital/Shop Address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='pickup_address',
            field=models.CharField(default='Unknown', help_text='Home Address', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='time_preference',
            field=models.CharField(default='ASAP', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
