# Generated by Django 5.2.5 on 2025-11-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_servicerequest_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='dropoff_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='dropoff_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='dropoff_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='pickup_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
